[workspace]
members = [
	"frame/block-reward",
	"frame/collator-selection",
	"frame/custom-signatures",
	"frame/dapps-staking",
	"frame/pallet-xcm",
	"frame/xc-asset-config",
	"frame/vesting",
	"primitives/xcm",
	"precompiles/assets-erc20",
	"precompiles/dapps-staking",
	"precompiles/substrate-ecdsa",
	"precompiles/sr25519",
	"precompiles/utils",
	"precompiles/xcm",
]
